#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "$0")" && pwd -P)
cd "${root}"

non_interactive=false
if [[ $# -eq 1 && "$1" == "--non-interactive" ]]; then
  non_interactive=true
elif [[ $# -ne 0 ]]; then
  echo "usage: ./start.sh [--non-interactive]" >&2
  exit 2
fi

for command in docker git python3 shasum; do
  command -v "${command}" >/dev/null 2>&1 || { echo "Required command not found: ${command}" >&2; exit 1; }
done

# shellcheck disable=SC1091
source "${root}/tools/runtime.sh"
harness_traps
echo "Preparing Kimi workspace..."
harness_init
docker info >/dev/null || { echo "Docker is not ready. Start Docker Desktop and retry." >&2; exit 1; }

MODULE_PIDS=()
MODULE_SESSION_FILES=()
COMPOSE_PID=""
stack_started=false

cleanup() {
  status=$?
  trap - EXIT INT TERM ERR
  set +e
  for pid in ${MODULE_PIDS[@]+"${MODULE_PIDS[@]}"} "${COMPOSE_PID}"; do
    if [[ -n "${pid}" ]]; then
      kill "${pid}" 2>/dev/null || true
    fi
  done
  for pid in ${MODULE_PIDS[@]+"${MODULE_PIDS[@]}"} "${COMPOSE_PID}"; do
    if [[ -n "${pid}" ]]; then
      wait "${pid}" 2>/dev/null || true
    fi
  done
  if [[ "${stack_started}" == true ]]; then
    harness_compose down --remove-orphans >/dev/null 2>&1 || true
  fi
  for file in proxy-token search-token nrp-api-key kimi-config.toml runtime.env session.env module.env compose/module-environment.json compose/resolved.json ${MODULE_SESSION_FILES[@]+"${MODULE_SESSION_FILES[@]}"}; do
    [[ -f "${HARNESS_RUNTIME_DIR}/${file}" ]] && find "${HARNESS_RUNTIME_DIR}/${file}" -delete
  done
  harness_unlock
  exit "${status}"
}
trap cleanup EXIT

platform_label=${HARNESS_PLATFORM_LABEL}
kimi_asset=${HARNESS_KIMI_ASSET}
workspace=${HARNESS_WORKSPACE}

export WORKSPACE_PATH=${workspace}
if [[ "$(uname -s)" == Darwin ]]; then
  export LOCAL_UID=1000 LOCAL_GID=1000
else
  export LOCAL_UID=${LOCAL_UID:-$(id -u)}
  export LOCAL_GID=${LOCAL_GID:-$(id -g)}
fi

export MODULE_NON_INTERACTIVE=${non_interactive}
module_args=()
[[ "${non_interactive}" == true ]] && module_args+=(--non-interactive)
python3 tools/modules.py select ${module_args[@]+"${module_args[@]}"}
harness_modules configure

state_file=${HARNESS_STATE_FILE}
session_file=${HARNESS_SESSION_FILE}
state_value() {
  if [[ -f "${state_file}" ]]; then
    python3 scripts/read_env.py "${state_file}" "$1" 2>/dev/null || true
  fi
}

installed_kimi=""
state_kimi=$(state_value KIMI_CODE_VERSION)
if [[ -n "${state_kimi}" ]]; then
  image_kimi=$(docker image inspect "adrc-kimi-agent:${HARNESS_IMAGE_SUFFIX}" --format '{{ index .Config.Labels "org.opencontainers.image.version" }}' 2>/dev/null || true)
  [[ "${image_kimi}" == "${state_kimi}" ]] && installed_kimi=${state_kimi}
fi

GITHUB_RELEASES_TOKEN=$(python3 scripts/read_env.py "${HARNESS_RESOLVED_BOOTSTRAP}" GITHUB_RELEASES_TOKEN 2>/dev/null || true)
export GITHUB_RELEASES_TOKEN
selector=(python3 scripts/select_versions.py --platform-label "${platform_label}" --kimi-asset "${kimi_asset}" --state "${state_file}" --output "${session_file}" --installed-kimi "${installed_kimi}")
[[ "${non_interactive}" == true ]] && selector+=(--non-interactive)
"${selector[@]}"

harness_modules select_version
python3 tools/modules.py environment ${module_args[@]+"${module_args[@]}"}
set -a
# shellcheck disable=SC1091
source "${HARNESS_RUNTIME_DIR}/module.env"
set +a

# Generated by scripts/select_versions.py from validated values.
set -a
# shellcheck disable=SC1090
source "${session_file}"
set +a

python3 tools/safe_workspace_init.py "${workspace}"
python3 tools/resource_check.py "${workspace}"
python3 tools/modules.py assemble

python3 tools/render_runtime.py --root "${root}" --runtime-dir "${HARNESS_RUNTIME_DIR}" --resolved-env "${HARNESS_RESOLVED_BOOTSTRAP}"
set -a
# shellcheck disable=SC1091
source "${HARNESS_RUNTIME_DIR}/runtime.env"
set +a

approval_manifest="${HARNESS_RUNTIME_DIR}/extension-approval.json"
python3 tools/approve_extensions.py prepare --workspace "${workspace}" --manifest "${approval_manifest}" --state-dir "${HARNESS_RUNTIME_DIR}" --output "${HARNESS_COMPOSE_DIR}/approved-extensions.yaml"

harness_modules prepare
harness_compose_files
harness_validate_compose
harness_modules verify

harness_modules install

harness_compose build
actual_kimi=$(harness_compose run -T --rm --no-deps kimi-agent kimi --version)
[[ "${actual_kimi}" == *"${KIMI_CODE_VERSION}"* ]] || { echo "Built Kimi version mismatch: ${actual_kimi}" >&2; exit 1; }
harness_modules check_build

cp -- "${session_file}" "${state_file}"
chmod 600 "${state_file}"
cp "${HARNESS_RUNTIME_DIR}/modules.json" "${HARNESS_RUNTIME_DIR}/last-modules.json"
find "${session_file}" -delete

wait_for_url() {
  local url=$1 token=${2:-} cafile=${3:-} attempts=${4:-120}
  local attempt
  for ((attempt=1; attempt<=attempts; attempt++)); do
    if [[ -n "${COMPOSE_PID:-}" ]] && ! kill -0 "${COMPOSE_PID}" 2>/dev/null; then
      return 1
    fi
    if URL_TO_CHECK="${url}" TOKEN_TO_CHECK="${token}" CA_TO_CHECK="${cafile}" python3 - <<'PY' >/dev/null 2>&1
import os, ssl, urllib.request
headers = {}
if os.environ.get("TOKEN_TO_CHECK"): headers["Authorization"] = f"Bearer {os.environ['TOKEN_TO_CHECK']}"
context = ssl.create_default_context(cafile=os.environ.get("CA_TO_CHECK") or None)
urllib.request.urlopen(urllib.request.Request(os.environ["URL_TO_CHECK"], headers=headers), timeout=3, context=context).read(1)
PY
    then return 0; fi
    sleep 1
  done
  return 1
}

harness_modules start
echo "Instance:  ${HARNESS_INSTANCE_ID}"
echo "Press Ctrl-C to stop everything."
echo

harness_modules verify
# searxng-init is expected to exit successfully during startup.
harness_compose up --remove-orphans --abort-on-container-failure &
COMPOSE_PID=$!
stack_started=true
if wait_for_url http://127.0.0.1:5494/api/v1/healthz "" "" 90; then
  harness_compose exec -T kimi-agent python3 /opt/kimi-runtime/tools/register_workspace.py
  echo "Kimi Code: http://127.0.0.1:5494 (workspace ready)"
  python3 tools/open_kimi_browser.py docker compose --env-file "${root}/.env" "${HARNESS_COMPOSE_FILES[@]}" || true
  if ! harness_compose exec -T kimi-agent /opt/serena/bin/python /opt/kimi-runtime/tools/check_services.py; then
    echo "Service checks need attention. The stack remains running; see docs/verification.md and rerun ./doctor.sh." >&2
  fi
else
  echo "Kimi web did not become ready for workspace registration; inspect the startup logs." >&2
  exit 1
fi
while kill -0 "${COMPOSE_PID}" 2>/dev/null; do
  for pid in ${MODULE_PIDS[@]+"${MODULE_PIDS[@]}"}; do
    kill -0 "${pid}" 2>/dev/null || { echo "A module process exited; inspect ${HARNESS_RUNTIME_DIR} logs" >&2; exit 1; }
  done
  sleep 1
done
wait "${COMPOSE_PID}"
