#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "$0")" && pwd -P)
cd "${root}"

non_interactive=false
if [[ $# -eq 1 && "$1" == "--non-interactive" ]]; then
  non_interactive=true
elif [[ $# -ne 0 ]]; then
  echo "usage: ./start.sh [--non-interactive]" >&2
  exit 2
fi

for command in docker git python3 shasum; do
  command -v "${command}" >/dev/null 2>&1 || { echo "Required command not found: ${command}" >&2; exit 1; }
done

# shellcheck disable=SC1091
source "${root}/tools/runtime.sh"
harness_traps
echo "Preparing Kimi workspace..."
harness_init
docker info >/dev/null || { echo "Docker is not ready. Start Docker Desktop and retry." >&2; exit 1; }

COMFY_PID=""
COMFY_BRIDGE_PID=""
COMPOSE_PID=""
stack_started=false

cleanup() {
  status=$?
  trap - EXIT INT TERM ERR
  set +e
  for pid in "${COMFY_BRIDGE_PID}" "${COMFY_PID}" "${COMPOSE_PID}"; do
    if [[ -n "${pid}" ]]; then
      kill "${pid}" 2>/dev/null || true
    fi
  done
  for pid in "${COMFY_BRIDGE_PID}" "${COMFY_PID}" "${COMPOSE_PID}"; do
    if [[ -n "${pid}" ]]; then
      wait "${pid}" 2>/dev/null || true
    fi
  done
  if [[ "${stack_started}" == true ]]; then
    harness_compose down --remove-orphans >/dev/null 2>&1 || true
  fi
  for file in proxy-token search-token bridge-token nrp-api-key kimi-config.toml runtime.env bridge.crt bridge.key session.env compose/resolved.json; do
    [[ -f "${HARNESS_RUNTIME_DIR}/${file}" ]] && find "${HARNESS_RUNTIME_DIR}/${file}" -delete
  done
  harness_unlock
  exit "${status}"
}
trap cleanup EXIT

platform_key=${HARNESS_PLATFORM}
platform_label=${HARNESS_PLATFORM_LABEL}
backend=${HARNESS_BACKEND}
kimi_asset=${HARNESS_KIMI_ASSET}
workspace=${HARNESS_WORKSPACE}

export WORKSPACE_PATH=${workspace}
if [[ "${backend}" == mps ]]; then
  export LOCAL_UID=1000 LOCAL_GID=1000
else
  export LOCAL_UID=${LOCAL_UID:-$(id -u)}
  export LOCAL_GID=${LOCAL_GID:-$(id -g)}
fi

set -a
# shellcheck disable=SC1091
source "${root}/comfy/backend.env"
set +a

state_file=${HARNESS_STATE_FILE}
session_file=${HARNESS_SESSION_FILE}
state_value() {
  if [[ -f "${state_file}" ]]; then
    python3 scripts/read_env.py "${state_file}" "$1" 2>/dev/null || true
  fi
}

installed_kimi=""
state_kimi=$(state_value KIMI_CODE_VERSION)
if [[ -n "${state_kimi}" ]]; then
  image_kimi=$(docker image inspect "adrc-kimi-agent:${HARNESS_IMAGE_SUFFIX}" --format '{{ index .Config.Labels "org.opencontainers.image.version" }}' 2>/dev/null || true)
  [[ "${image_kimi}" == "${state_kimi}" ]] && installed_kimi=${state_kimi}
fi

installed_comfy=""
state_comfy=$(state_value COMFYUI_VERSION)
if [[ -n "${state_comfy}" ]]; then
  if [[ "${backend}" == mps ]]; then
    current="${root}/.local/comfy-macos/${HARNESS_INSTANCE_ID}/current"
    [[ -x "${current}/venv/bin/python" && -f "${current}/VERSION" && "$(<"${current}/VERSION")" == "${state_comfy}" ]] && installed_comfy=${state_comfy}
  else
    image_comfy=$(docker image inspect "adrc-comfyui-cuda:${HARNESS_IMAGE_SUFFIX}" --format '{{ index .Config.Labels "org.opencontainers.image.version" }}' 2>/dev/null || true)
    [[ "${image_comfy}" == "${state_comfy}" ]] && installed_comfy=${state_comfy}
  fi
fi

GITHUB_RELEASES_TOKEN=$(python3 scripts/read_env.py "${HARNESS_RESOLVED_BOOTSTRAP}" GITHUB_RELEASES_TOKEN 2>/dev/null || true)
export GITHUB_RELEASES_TOKEN
selector=(python3 scripts/select_versions.py --platform-key "${platform_key}" --platform-label "${platform_label}" --kimi-asset "${kimi_asset}" --state "${state_file}" --output "${session_file}" --installed-kimi "${installed_kimi}" --installed-comfy "${installed_comfy}")
[[ "${non_interactive}" == true ]] && selector+=(--non-interactive)
"${selector[@]}"

if [[ "${backend}" == mps ]]; then
  mac_python=$(bash "${root}/scripts/select_macos_python.sh")
fi

# Generated by scripts/select_versions.py from validated values.
set -a
# shellcheck disable=SC1090
source "${session_file}"
set +a

python3 tools/safe_workspace_init.py "${workspace}"
python3 tools/resource_check.py "${workspace}"
bind_manifest="${HARNESS_RUNTIME_DIR}/binds.json"
bind_assignments=$(python3 tools/verify_bind_paths.py record "${workspace}" "${bind_manifest}")
while IFS= read -r assignment; do
  variable=${assignment%%=*}
  export "${variable}=${assignment#*=}"
done <<<"${bind_assignments}"

python3 tools/render_runtime.py --root "${root}" --runtime-dir "${HARNESS_RUNTIME_DIR}" --resolved-env "${HARNESS_RESOLVED_BOOTSTRAP}"
set -a
# shellcheck disable=SC1091
source "${HARNESS_RUNTIME_DIR}/runtime.env"
set +a

approval_manifest="${HARNESS_RUNTIME_DIR}/extension-approval.json"
python3 tools/approve_extensions.py prepare --workspace "${workspace}" --manifest "${approval_manifest}" --state-dir "${HARNESS_RUNTIME_DIR}" --output "${HARNESS_COMPOSE_DIR}/approved-extensions.yaml"

if [[ "${backend}" == mps ]]; then
  command -v openssl >/dev/null 2>&1 || { echo "Required command not found: openssl" >&2; exit 1; }
  COMFYUI_BRIDGE_CERT="${HARNESS_RUNTIME_DIR}/bridge.crt"
  COMFYUI_BRIDGE_KEY="${HARNESS_RUNTIME_DIR}/bridge.key"
  export COMFYUI_BRIDGE_CERT COMFYUI_BRIDGE_KEY
  # shell.sh and acceptance.sh also need the certificate path for Compose.
  printf 'export COMFYUI_BRIDGE_CERT=%q\n' "${COMFYUI_BRIDGE_CERT}" >>"${HARNESS_RUNTIME_DIR}/runtime.env"
  openssl req -x509 -newkey rsa:3072 -sha256 -nodes -days 2 \
    -config "${root}/runtime/openssl-bridge.cnf" \
    -keyout "${COMFYUI_BRIDGE_KEY}" -out "${COMFYUI_BRIDGE_CERT}" >/dev/null 2>&1
  chmod 600 "${COMFYUI_BRIDGE_KEY}" "${COMFYUI_BRIDGE_CERT}"
fi

harness_compose_files
harness_validate_compose
python3 tools/verify_bind_paths.py verify "${workspace}" "${bind_manifest}"

if [[ "${backend}" == mps ]]; then
  bash scripts/install_comfy_macos.sh "${root}" "${workspace}" "${COMFYUI_VERSION}" "${COMFYUI_COMMIT}" "${mac_python}" "${HARNESS_INSTANCE_ID}"
fi

harness_compose build
actual_kimi=$(harness_compose run -T --rm --no-deps kimi-agent kimi --version)
[[ "${actual_kimi}" == *"${KIMI_CODE_VERSION}"* ]] || { echo "Built Kimi version mismatch: ${actual_kimi}" >&2; exit 1; }
if [[ "${backend}" == cuda ]]; then
  harness_compose run --rm --no-deps comfyui python -c 'import torch; assert torch.cuda.is_available(); print(torch.cuda.get_device_name())'
fi

cp -- "${session_file}" "${state_file}"
chmod 600 "${state_file}"
find "${session_file}" -delete

wait_for_url() {
  local url=$1 token=${2:-} cafile=${3:-} attempts=${4:-120}
  local attempt
  for ((attempt=1; attempt<=attempts; attempt++)); do
    if URL_TO_CHECK="${url}" TOKEN_TO_CHECK="${token}" CA_TO_CHECK="${cafile}" python3 - <<'PY' >/dev/null 2>&1
import os, ssl, urllib.request
headers = {}
if os.environ.get("TOKEN_TO_CHECK"): headers["Authorization"] = f"Bearer {os.environ['TOKEN_TO_CHECK']}"
context = ssl.create_default_context(cafile=os.environ.get("CA_TO_CHECK") or None)
urllib.request.urlopen(urllib.request.Request(os.environ["URL_TO_CHECK"], headers=headers), timeout=3, context=context).read(1)
PY
    then return 0; fi
    sleep 1
  done
  return 1
}

if [[ "${backend}" == mps ]]; then
  comfy_home="${root}/.local/comfy-macos/${HARNESS_INSTANCE_ID}/current"
  comfy_log="${HARNESS_RUNTIME_DIR}/comfyui.log"
  bridge_log="${HARNESS_RUNTIME_DIR}/comfy-bridge.log"
  (
    cd "${comfy_home}/app"
    exec env PYTORCH_ENABLE_MPS_FALLBACK=1 "${comfy_home}/venv/bin/python" main.py \
      --listen 127.0.0.1 --port 8188 --disable-auto-launch \
      --user-directory "${COMFYUI_USER_PATH}" --input-directory "${COMFYUI_INPUT_PATH}" \
      --output-directory "${COMFYUI_OUTPUT_PATH}" --temp-directory "${COMFYUI_TEMP_PATH}"
  ) >"${comfy_log}" 2>&1 &
  COMFY_PID=$!
  wait_for_url http://127.0.0.1:8188/system_stats "" "" 180 || { echo "ComfyUI did not become ready. See ${comfy_log}" >&2; exit 1; }
  COMFYUI_TOKEN=${COMFYUI_TOKEN} "${comfy_home}/venv/bin/python" scripts/comfy_bridge.py \
    --host 0.0.0.0 --port 8190 --upstream http://127.0.0.1:8188 \
    --tls-cert "${COMFYUI_BRIDGE_CERT}" --tls-key "${COMFYUI_BRIDGE_KEY}" \
    --max-body "${COMFYUI_BRIDGE_MAX_BODY:-536870912}" \
    --max-ws-message "${COMFYUI_BRIDGE_MAX_WS_MESSAGE:-67108864}" \
    --max-connections "${COMFYUI_BRIDGE_MAX_CONNECTIONS:-16}" >"${bridge_log}" 2>&1 &
  COMFY_BRIDGE_PID=$!
  wait_for_url https://127.0.0.1:8190/system_stats "${COMFYUI_TOKEN}" "${COMFYUI_BRIDGE_CERT}" 30 || { echo "ComfyUI bridge did not become ready. See ${bridge_log}" >&2; exit 1; }
fi

echo
echo "Kimi Code: http://127.0.0.1:5494"
echo "ComfyUI:   http://127.0.0.1:8188"
echo "Backend:   ${backend}"
echo "Instance:  ${HARNESS_INSTANCE_ID}"
echo "Press Ctrl-C to stop everything."
echo

python3 tools/verify_bind_paths.py verify "${workspace}" "${bind_manifest}"
# searxng-init is expected to exit successfully during startup.
harness_compose up --remove-orphans --abort-on-container-failure &
COMPOSE_PID=$!
stack_started=true
while kill -0 "${COMPOSE_PID}" 2>/dev/null; do
  [[ -n "${COMFY_PID}" ]] && ! kill -0 "${COMFY_PID}" 2>/dev/null && { echo "Native ComfyUI exited; see ${HARNESS_RUNTIME_DIR}/comfyui.log" >&2; exit 1; }
  [[ -n "${COMFY_BRIDGE_PID}" ]] && ! kill -0 "${COMFY_BRIDGE_PID}" 2>/dev/null && { echo "ComfyUI bridge exited; see ${HARNESS_RUNTIME_DIR}/comfy-bridge.log" >&2; exit 1; }
  sleep 1
done
wait "${COMPOSE_PID}"
