#!/usr/bin/env python3
"""Render the model and provider half of Kimi's config from a resolved plan.

Kimi selects a model by alias, and an alias binds to a provider, which binds to an endpoint.
That chain is exactly the information ``./models`` and ``./providers`` already hold, so it is
generated instead of written twice: this module is the only place that knows how a definition
becomes ``[providers.*]``, ``[models.*]`` and ``[secondary_model]`` tables.

The output is appended to the static baseline in ``runtime/config.toml``, which is why every
key here must be a table rather than a top-level scalar.
"""

from __future__ import annotations

from typing import Any

if __package__:
    from .definitions import LANES
else:
    from definitions import LANES


#: Each lane reaches the proxy through its own route, so the proxy can tell which policy a
#: request was admitted under without trusting a header the client controls.
ROUTE_TEMPLATE = "http://model-proxy:8080/{lane}/v1"


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_string_array(values: list[str]) -> str:
    return "[" + ", ".join(_quote(value) for value in values) + "]"


def provider_table(name: str, protocol: str, lane: str, token: str) -> list[str]:
    return [
        f"[providers.{name}]",
        f"type = {_quote(protocol)}",
        f"base_url = {_quote(ROUTE_TEMPLATE.format(lane=lane))}",
        # Kimi sends this as the bearer token; the proxy checks it and swaps in the real
        # provider credential, which never enters the agent's filesystem.
        f"api_key = {_quote(token)}",
        "",
    ]


def model_table(entry: dict[str, Any]) -> list[str]:
    lines = [
        f"[models.{entry['alias']}]",
        f"provider = {_quote(entry['provider_name'])}",
        f"model = {_quote(entry['model'])}",
        f"max_context_size = {entry['context_tokens']}",
        f"max_input_size = {entry['input_tokens']}",
    ]
    if entry["capabilities"]:
        lines.append(f"capabilities = {emit_string_array(entry['capabilities'])}")
    if entry["support_efforts"]:
        lines.append(f"support_efforts = {emit_string_array(entry['support_efforts'])}")
    if entry["default_effort"]:
        lines.append(f"default_effort = {_quote(entry['default_effort'])}")
    lines.append(f"display_name = {_quote(entry['display_name'])}")
    lines.append("")
    return lines


def render(plan: dict[str, Any], placeholder: str = "__MODEL_PROXY_TOKEN__") -> str:
    """Return the generated TOML fragment for one resolved plan.

    ``placeholder`` stays unevaluated when the fragment will be substituted together
    with the launcher's per-instance proxy token, so no rendered file ever holds a secret that
    the launcher does not already own.
    """
    lanes = plan["lanes"]
    # Every lane below is skipped when absent, and this one is not: the binding is what stops a
    # large primary context being inherited by every child. Absent means the plan is wrong, and
    # that has to be a refusal the launcher prints rather than a traceback it forwards.
    subagent = lanes.get("subagent")
    if subagent is None:
        raise ValueError("the resolved plan has no subagent lane to bind")
    lines = [
        "# ------------------------------------------------------------",
        "# GENERATED by tools/render_runtime.py from ./models and ./providers.",
        "# Edit those definitions and restart; a change here is discarded at the next launch.",
        "# ------------------------------------------------------------",
        "",
    ]
    for name in LANES:
        if name not in lanes:
            continue
        lane = lanes[name]
        lines += provider_table(
            lane["provider_name"],
            plan["providers"][lane["provider"]]["protocol"],
            name,
            placeholder,
        )
    for name in LANES:
        if name in lanes:
            lines += model_table(lanes[name])

    # The binding is what keeps a large primary context from being inherited by every child,
    # which would multiply one request's cost by the fan-out and break the resolved budget.
    lines += [
        "[secondary_model]",
        f"default_model = {_quote(subagent['alias'])}",
        "force = true",
    ]
    if subagent["default_effort"]:
        lines.append(f"default_effort = {_quote(subagent['default_effort'])}")
    return "\n".join(lines).rstrip("\n") + "\n"
