use_default_settings: true

general:
  instance_name: "Kimi local search"
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - json

server:
  limiter: false
  image_proxy: false
